// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hot_product.sql

package sqldb

import (
	"context"
	"time"
)

const deleteHotProductsBefore = `-- name: DeleteHotProductsBefore :execrows
DELETE FROM gugu.hot_product
WHERE collected_date < $1
`

func (q *Queries) DeleteHotProductsBefore(ctx context.Context, collectedDate time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteHotProductsBefore, collectedDate)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertHotProduct = `-- name: InsertHotProduct :exec
INSERT INTO gugu.hot_product (
    id, external_product_id, title, image_url, product_url,
    sale_price, currency, collected_date, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) ON CONFLICT (external_product_id, collected_date) DO NOTHING
`

type InsertHotProductParams struct {
	ID                string    `json:"id"`
	ExternalProductID string    `json:"external_product_id"`
	Title             string    `json:"title"`
	ImageUrl          string    `json:"image_url"`
	ProductUrl        string    `json:"product_url"`
	SalePrice         string    `json:"sale_price"`
	Currency          string    `json:"currency"`
	CollectedDate     time.Time `json:"collected_date"`
	CreatedAt         time.Time `json:"created_at"`
}

func (q *Queries) InsertHotProduct(ctx context.Context, arg InsertHotProductParams) error {
	_, err := q.db.ExecContext(ctx, insertHotProduct,
		arg.ID,
		arg.ExternalProductID,
		arg.Title,
		arg.ImageUrl,
		arg.ProductUrl,
		arg.SalePrice,
		arg.Currency,
		arg.CollectedDate,
		arg.CreatedAt,
	)
	return err
}

const listHotProductsByDate = `-- name: ListHotProductsByDate :many
SELECT id, external_product_id, title, image_url, product_url,
       sale_price, currency, collected_date, created_at
FROM gugu.hot_product
WHERE collected_date = $1
ORDER BY created_at
`

func (q *Queries) ListHotProductsByDate(ctx context.Context, collectedDate time.Time) ([]GuguHotProduct, error) {
	rows, err := q.db.QueryContext(ctx, listHotProductsByDate, collectedDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GuguHotProduct{}
	for rows.Next() {
		var i GuguHotProduct
		if err := rows.Scan(
			&i.ID,
			&i.ExternalProductID,
			&i.Title,
			&i.ImageUrl,
			&i.ProductUrl,
			&i.SalePrice,
			&i.Currency,
			&i.CollectedDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHotProductsLatest = `-- name: ListHotProductsLatest :many
SELECT id, external_product_id, title, image_url, product_url,
       sale_price, currency, collected_date, created_at
FROM gugu.hot_product
WHERE collected_date = (SELECT MAX(collected_date) FROM gugu.hot_product)
ORDER BY created_at
`

func (q *Queries) ListHotProductsLatest(ctx context.Context) ([]GuguHotProduct, error) {
	rows, err := q.db.QueryContext(ctx, listHotProductsLatest)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GuguHotProduct{}
	for rows.Next() {
		var i GuguHotProduct
		if err := rows.Scan(
			&i.ID,
			&i.ExternalProductID,
			&i.Title,
			&i.ImageUrl,
			&i.ProductUrl,
			&i.SalePrice,
			&i.Currency,
			&i.CollectedDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
