// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package sqldb

import (
	"context"
	"time"

	"github.com/lib/pq"
)

const createProduct = `-- name: CreateProduct :exec
INSERT INTO gugu.product (
    id, market, external_product_id, original_url, title, main_image_url,
    current_price, currency, product_url, collection_source,
    last_collected_at, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
`

type CreateProductParams struct {
	ID                string    `json:"id"`
	Market            string    `json:"market"`
	ExternalProductID string    `json:"external_product_id"`
	OriginalUrl       string    `json:"original_url"`
	Title             string    `json:"title"`
	MainImageUrl      string    `json:"main_image_url"`
	CurrentPrice      string    `json:"current_price"`
	Currency          string    `json:"currency"`
	ProductUrl        string    `json:"product_url"`
	CollectionSource  string    `json:"collection_source"`
	LastCollectedAt   time.Time `json:"last_collected_at"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) error {
	_, err := q.db.ExecContext(ctx, createProduct,
		arg.ID,
		arg.Market,
		arg.ExternalProductID,
		arg.OriginalUrl,
		arg.Title,
		arg.MainImageUrl,
		arg.CurrentPrice,
		arg.Currency,
		arg.ProductUrl,
		arg.CollectionSource,
		arg.LastCollectedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const findProductByID = `-- name: FindProductByID :one
SELECT id, market, external_product_id, original_url, title, main_image_url,
       current_price, currency, product_url, collection_source,
       last_collected_at, created_at, updated_at
FROM gugu.product
WHERE id = $1
`

func (q *Queries) FindProductByID(ctx context.Context, id string) (GuguProduct, error) {
	row := q.db.QueryRowContext(ctx, findProductByID, id)
	var i GuguProduct
	err := row.Scan(
		&i.ID,
		&i.Market,
		&i.ExternalProductID,
		&i.OriginalUrl,
		&i.Title,
		&i.MainImageUrl,
		&i.CurrentPrice,
		&i.Currency,
		&i.ProductUrl,
		&i.CollectionSource,
		&i.LastCollectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findProductByMarketAndExternalProductID = `-- name: FindProductByMarketAndExternalProductID :one
SELECT id, market, external_product_id, original_url, title, main_image_url,
       current_price, currency, product_url, collection_source,
       last_collected_at, created_at, updated_at
FROM gugu.product
WHERE market = $1 AND external_product_id = $2
`

type FindProductByMarketAndExternalProductIDParams struct {
	Market            string `json:"market"`
	ExternalProductID string `json:"external_product_id"`
}

func (q *Queries) FindProductByMarketAndExternalProductID(ctx context.Context, arg FindProductByMarketAndExternalProductIDParams) (GuguProduct, error) {
	row := q.db.QueryRowContext(ctx, findProductByMarketAndExternalProductID, arg.Market, arg.ExternalProductID)
	var i GuguProduct
	err := row.Scan(
		&i.ID,
		&i.Market,
		&i.ExternalProductID,
		&i.OriginalUrl,
		&i.Title,
		&i.MainImageUrl,
		&i.CurrentPrice,
		&i.Currency,
		&i.ProductUrl,
		&i.CollectionSource,
		&i.LastCollectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findProductsByIDs = `-- name: FindProductsByIDs :many
SELECT id, market, external_product_id, original_url, title, main_image_url,
       current_price, currency, product_url, collection_source,
       last_collected_at, created_at, updated_at
FROM gugu.product
WHERE id = ANY($1::text[])
`

func (q *Queries) FindProductsByIDs(ctx context.Context, dollar_1 []string) ([]GuguProduct, error) {
	rows, err := q.db.QueryContext(ctx, findProductsByIDs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GuguProduct{}
	for rows.Next() {
		var i GuguProduct
		if err := rows.Scan(
			&i.ID,
			&i.Market,
			&i.ExternalProductID,
			&i.OriginalUrl,
			&i.Title,
			&i.MainImageUrl,
			&i.CurrentPrice,
			&i.Currency,
			&i.ProductUrl,
			&i.CollectionSource,
			&i.LastCollectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllProducts = `-- name: ListAllProducts :many
SELECT id, market, external_product_id, original_url, title, main_image_url,
       current_price, currency, product_url, collection_source,
       last_collected_at, created_at, updated_at
FROM gugu.product
ORDER BY created_at
`

func (q *Queries) ListAllProducts(ctx context.Context) ([]GuguProduct, error) {
	rows, err := q.db.QueryContext(ctx, listAllProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GuguProduct{}
	for rows.Next() {
		var i GuguProduct
		if err := rows.Scan(
			&i.ID,
			&i.Market,
			&i.ExternalProductID,
			&i.OriginalUrl,
			&i.Title,
			&i.MainImageUrl,
			&i.CurrentPrice,
			&i.Currency,
			&i.ProductUrl,
			&i.CollectionSource,
			&i.LastCollectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceUpdateCandidateProducts = `-- name: ListPriceUpdateCandidateProducts :many
SELECT id, market, external_product_id, original_url, title, main_image_url,
       current_price, currency, product_url, collection_source,
       last_collected_at, created_at, updated_at
FROM gugu.product
WHERE ($1::text = '' OR collection_source = $1)
  AND ($2::text = '' OR market = $2)
  AND ($3::timestamptz = '0001-01-01 00:00:00+00'::timestamptz OR last_collected_at <= $3)
ORDER BY last_collected_at, created_at
`

type ListPriceUpdateCandidateProductsParams struct {
	Column1 string    `json:"column_1"`
	Column2 string    `json:"column_2"`
	Column3 time.Time `json:"column_3"`
}

func (q *Queries) ListPriceUpdateCandidateProducts(ctx context.Context, arg ListPriceUpdateCandidateProductsParams) ([]GuguProduct, error) {
	rows, err := q.db.QueryContext(ctx, listPriceUpdateCandidateProducts, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GuguProduct{}
	for rows.Next() {
		var i GuguProduct
		if err := rows.Scan(
			&i.ID,
			&i.Market,
			&i.ExternalProductID,
			&i.OriginalUrl,
			&i.Title,
			&i.MainImageUrl,
			&i.CurrentPrice,
			&i.Currency,
			&i.ProductUrl,
			&i.CollectionSource,
			&i.LastCollectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByCollectionSource = `-- name: ListProductsByCollectionSource :many
SELECT id, market, external_product_id, original_url, title, main_image_url,
       current_price, currency, product_url, collection_source,
       last_collected_at, created_at, updated_at
FROM gugu.product
WHERE collection_source = $1
ORDER BY created_at
`

func (q *Queries) ListProductsByCollectionSource(ctx context.Context, collectionSource string) ([]GuguProduct, error) {
	rows, err := q.db.QueryContext(ctx, listProductsByCollectionSource, collectionSource)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GuguProduct{}
	for rows.Next() {
		var i GuguProduct
		if err := rows.Scan(
			&i.ID,
			&i.Market,
			&i.ExternalProductID,
			&i.OriginalUrl,
			&i.Title,
			&i.MainImageUrl,
			&i.CurrentPrice,
			&i.Currency,
			&i.ProductUrl,
			&i.CollectionSource,
			&i.LastCollectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByMarket = `-- name: ListProductsByMarket :many
SELECT id, market, external_product_id, original_url, title, main_image_url,
       current_price, currency, product_url, collection_source,
       last_collected_at, created_at, updated_at
FROM gugu.product
WHERE market = $1
ORDER BY created_at
`

func (q *Queries) ListProductsByMarket(ctx context.Context, market string) ([]GuguProduct, error) {
	rows, err := q.db.QueryContext(ctx, listProductsByMarket, market)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GuguProduct{}
	for rows.Next() {
		var i GuguProduct
		if err := rows.Scan(
			&i.ID,
			&i.Market,
			&i.ExternalProductID,
			&i.OriginalUrl,
			&i.Title,
			&i.MainImageUrl,
			&i.CurrentPrice,
			&i.Currency,
			&i.ProductUrl,
			&i.CollectionSource,
			&i.LastCollectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsWithoutSKUs = `-- name: ListProductsWithoutSKUs :many
SELECT p.id, p.market, p.external_product_id, p.original_url, p.title,
       p.main_image_url, p.current_price, p.currency, p.product_url,
       p.collection_source, p.last_collected_at, p.created_at, p.updated_at
FROM gugu.product p
LEFT JOIN gugu.sku s ON p.id = s.product_id
WHERE s.id IS NULL
ORDER BY p.created_at
`

func (q *Queries) ListProductsWithoutSKUs(ctx context.Context) ([]GuguProduct, error) {
	rows, err := q.db.QueryContext(ctx, listProductsWithoutSKUs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GuguProduct{}
	for rows.Next() {
		var i GuguProduct
		if err := rows.Scan(
			&i.ID,
			&i.Market,
			&i.ExternalProductID,
			&i.OriginalUrl,
			&i.Title,
			&i.MainImageUrl,
			&i.CurrentPrice,
			&i.Currency,
			&i.ProductUrl,
			&i.CollectionSource,
			&i.LastCollectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :execrows
UPDATE gugu.product
SET original_url = $2, title = $3, main_image_url = $4,
    current_price = $5, currency = $6, product_url = $7,
    collection_source = $8, last_collected_at = $9, updated_at = $10
WHERE id = $1
`

type UpdateProductParams struct {
	ID               string    `json:"id"`
	OriginalUrl      string    `json:"original_url"`
	Title            string    `json:"title"`
	MainImageUrl     string    `json:"main_image_url"`
	CurrentPrice     string    `json:"current_price"`
	Currency         string    `json:"currency"`
	ProductUrl       string    `json:"product_url"`
	CollectionSource string    `json:"collection_source"`
	LastCollectedAt  time.Time `json:"last_collected_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateProduct,
		arg.ID,
		arg.OriginalUrl,
		arg.Title,
		arg.MainImageUrl,
		arg.CurrentPrice,
		arg.Currency,
		arg.ProductUrl,
		arg.CollectionSource,
		arg.LastCollectedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
