// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package sqldb

import (
	"context"
	"time"

	"github.com/lib/pq"
)

const createProduct = `-- name: CreateProduct :exec
INSERT INTO gugu.product (
    id, market, origin_product_id, original_url, title, main_image_url,
    product_url, collection_source, last_collected_at, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
`

type CreateProductParams struct {
	ID               string    `json:"id"`
	Market           string    `json:"market"`
	OriginProductID  string    `json:"origin_product_id"`
	OriginalUrl      string    `json:"original_url"`
	Title            string    `json:"title"`
	MainImageUrl     string    `json:"main_image_url"`
	ProductUrl       string    `json:"product_url"`
	CollectionSource string    `json:"collection_source"`
	LastCollectedAt  time.Time `json:"last_collected_at"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) error {
	_, err := q.db.ExecContext(ctx, createProduct,
		arg.ID,
		arg.Market,
		arg.OriginProductID,
		arg.OriginalUrl,
		arg.Title,
		arg.MainImageUrl,
		arg.ProductUrl,
		arg.CollectionSource,
		arg.LastCollectedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const findProductByID = `-- name: FindProductByID :one
SELECT id, market, origin_product_id AS external_product_id, original_url, title, main_image_url,
       product_url, collection_source, last_collected_at, created_at, updated_at
FROM gugu.product
WHERE id = $1
`

type FindProductByIDRow struct {
	ID                string    `json:"id"`
	Market            string    `json:"market"`
	ExternalProductID string    `json:"external_product_id"`
	OriginalUrl       string    `json:"original_url"`
	Title             string    `json:"title"`
	MainImageUrl      string    `json:"main_image_url"`
	ProductUrl        string    `json:"product_url"`
	CollectionSource  string    `json:"collection_source"`
	LastCollectedAt   time.Time `json:"last_collected_at"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

func (q *Queries) FindProductByID(ctx context.Context, id string) (FindProductByIDRow, error) {
	row := q.db.QueryRowContext(ctx, findProductByID, id)
	var i FindProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.Market,
		&i.ExternalProductID,
		&i.OriginalUrl,
		&i.Title,
		&i.MainImageUrl,
		&i.ProductUrl,
		&i.CollectionSource,
		&i.LastCollectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findProductByMarketAndExternalProductID = `-- name: FindProductByMarketAndExternalProductID :one
SELECT id, market, origin_product_id AS external_product_id, original_url, title, main_image_url,
       product_url, collection_source, last_collected_at, created_at, updated_at
FROM gugu.product
WHERE market = $1 AND origin_product_id = $2
`

type FindProductByMarketAndExternalProductIDParams struct {
	Market          string `json:"market"`
	OriginProductID string `json:"origin_product_id"`
}

type FindProductByMarketAndExternalProductIDRow struct {
	ID                string    `json:"id"`
	Market            string    `json:"market"`
	ExternalProductID string    `json:"external_product_id"`
	OriginalUrl       string    `json:"original_url"`
	Title             string    `json:"title"`
	MainImageUrl      string    `json:"main_image_url"`
	ProductUrl        string    `json:"product_url"`
	CollectionSource  string    `json:"collection_source"`
	LastCollectedAt   time.Time `json:"last_collected_at"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

func (q *Queries) FindProductByMarketAndExternalProductID(ctx context.Context, arg FindProductByMarketAndExternalProductIDParams) (FindProductByMarketAndExternalProductIDRow, error) {
	row := q.db.QueryRowContext(ctx, findProductByMarketAndExternalProductID, arg.Market, arg.OriginProductID)
	var i FindProductByMarketAndExternalProductIDRow
	err := row.Scan(
		&i.ID,
		&i.Market,
		&i.ExternalProductID,
		&i.OriginalUrl,
		&i.Title,
		&i.MainImageUrl,
		&i.ProductUrl,
		&i.CollectionSource,
		&i.LastCollectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findProductsByIDs = `-- name: FindProductsByIDs :many
SELECT id, market, origin_product_id AS external_product_id, original_url, title, main_image_url,
       product_url, collection_source, last_collected_at, created_at, updated_at
FROM gugu.product
WHERE id = ANY($1::text[])
`

type FindProductsByIDsRow struct {
	ID                string    `json:"id"`
	Market            string    `json:"market"`
	ExternalProductID string    `json:"external_product_id"`
	OriginalUrl       string    `json:"original_url"`
	Title             string    `json:"title"`
	MainImageUrl      string    `json:"main_image_url"`
	ProductUrl        string    `json:"product_url"`
	CollectionSource  string    `json:"collection_source"`
	LastCollectedAt   time.Time `json:"last_collected_at"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

func (q *Queries) FindProductsByIDs(ctx context.Context, dollar_1 []string) ([]FindProductsByIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, findProductsByIDs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindProductsByIDsRow{}
	for rows.Next() {
		var i FindProductsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Market,
			&i.ExternalProductID,
			&i.OriginalUrl,
			&i.Title,
			&i.MainImageUrl,
			&i.ProductUrl,
			&i.CollectionSource,
			&i.LastCollectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveTrackedProductIDs = `-- name: ListActiveTrackedProductIDs :many
SELECT DISTINCT product_id
FROM gugu.user_tracked_item
WHERE deleted_at IS NULL
ORDER BY product_id
`

func (q *Queries) ListActiveTrackedProductIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listActiveTrackedProductIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var product_id string
		if err := rows.Scan(&product_id); err != nil {
			return nil, err
		}
		items = append(items, product_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllLocalizedProducts = `-- name: ListAllLocalizedProducts :many
SELECT
    p.id,
    p.market,
    p.origin_product_id AS external_product_id,
    p.original_url,
    COALESCE(pl.title, p.title) AS title,
    COALESCE(pl.main_image_url, p.main_image_url) AS main_image_url,
    COALESCE(pl.product_url, p.product_url) AS product_url,
    p.collection_source,
    p.last_collected_at,
    p.created_at,
    GREATEST(p.updated_at, COALESCE(pl.updated_at, p.updated_at))::timestamptz AS updated_at
FROM gugu.product p
LEFT JOIN gugu.product_localization pl
    ON pl.product_id = p.id
   AND pl.language = $1
ORDER BY p.created_at
`

type ListAllLocalizedProductsRow struct {
	ID                string    `json:"id"`
	Market            string    `json:"market"`
	ExternalProductID string    `json:"external_product_id"`
	OriginalUrl       string    `json:"original_url"`
	Title             string    `json:"title"`
	MainImageUrl      string    `json:"main_image_url"`
	ProductUrl        string    `json:"product_url"`
	CollectionSource  string    `json:"collection_source"`
	LastCollectedAt   time.Time `json:"last_collected_at"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

func (q *Queries) ListAllLocalizedProducts(ctx context.Context, language string) ([]ListAllLocalizedProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllLocalizedProducts, language)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllLocalizedProductsRow{}
	for rows.Next() {
		var i ListAllLocalizedProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Market,
			&i.ExternalProductID,
			&i.OriginalUrl,
			&i.Title,
			&i.MainImageUrl,
			&i.ProductUrl,
			&i.CollectionSource,
			&i.LastCollectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllProducts = `-- name: ListAllProducts :many
SELECT id, market, origin_product_id AS external_product_id, original_url, title, main_image_url,
       product_url, collection_source, last_collected_at, created_at, updated_at
FROM gugu.product
ORDER BY created_at
`

type ListAllProductsRow struct {
	ID                string    `json:"id"`
	Market            string    `json:"market"`
	ExternalProductID string    `json:"external_product_id"`
	OriginalUrl       string    `json:"original_url"`
	Title             string    `json:"title"`
	MainImageUrl      string    `json:"main_image_url"`
	ProductUrl        string    `json:"product_url"`
	CollectionSource  string    `json:"collection_source"`
	LastCollectedAt   time.Time `json:"last_collected_at"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

func (q *Queries) ListAllProducts(ctx context.Context) ([]ListAllProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllProductsRow{}
	for rows.Next() {
		var i ListAllProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Market,
			&i.ExternalProductID,
			&i.OriginalUrl,
			&i.Title,
			&i.MainImageUrl,
			&i.ProductUrl,
			&i.CollectionSource,
			&i.LastCollectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocalizedProductsByCollectionSource = `-- name: ListLocalizedProductsByCollectionSource :many
SELECT
    p.id,
    p.market,
    p.origin_product_id AS external_product_id,
    p.original_url,
    COALESCE(pl.title, p.title) AS title,
    COALESCE(pl.main_image_url, p.main_image_url) AS main_image_url,
    COALESCE(pl.product_url, p.product_url) AS product_url,
    p.collection_source,
    p.last_collected_at,
    p.created_at,
    GREATEST(p.updated_at, COALESCE(pl.updated_at, p.updated_at))::timestamptz AS updated_at
FROM gugu.product p
LEFT JOIN gugu.product_localization pl
    ON pl.product_id = p.id
   AND pl.language = $2
WHERE p.collection_source = $1
ORDER BY p.created_at
`

type ListLocalizedProductsByCollectionSourceParams struct {
	CollectionSource string `json:"collection_source"`
	Language         string `json:"language"`
}

type ListLocalizedProductsByCollectionSourceRow struct {
	ID                string    `json:"id"`
	Market            string    `json:"market"`
	ExternalProductID string    `json:"external_product_id"`
	OriginalUrl       string    `json:"original_url"`
	Title             string    `json:"title"`
	MainImageUrl      string    `json:"main_image_url"`
	ProductUrl        string    `json:"product_url"`
	CollectionSource  string    `json:"collection_source"`
	LastCollectedAt   time.Time `json:"last_collected_at"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

func (q *Queries) ListLocalizedProductsByCollectionSource(ctx context.Context, arg ListLocalizedProductsByCollectionSourceParams) ([]ListLocalizedProductsByCollectionSourceRow, error) {
	rows, err := q.db.QueryContext(ctx, listLocalizedProductsByCollectionSource, arg.CollectionSource, arg.Language)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLocalizedProductsByCollectionSourceRow{}
	for rows.Next() {
		var i ListLocalizedProductsByCollectionSourceRow
		if err := rows.Scan(
			&i.ID,
			&i.Market,
			&i.ExternalProductID,
			&i.OriginalUrl,
			&i.Title,
			&i.MainImageUrl,
			&i.ProductUrl,
			&i.CollectionSource,
			&i.LastCollectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceUpdateCandidateProducts = `-- name: ListPriceUpdateCandidateProducts :many
SELECT id, market, origin_product_id AS external_product_id, original_url, title, main_image_url,
       product_url, collection_source,
       last_collected_at, created_at, updated_at
FROM gugu.product
WHERE ($1::text = '' OR collection_source = $1)
  AND ($2::text = '' OR market = $2)
  AND ($3::timestamptz = '0001-01-01 00:00:00+00'::timestamptz OR last_collected_at <= $3)
ORDER BY last_collected_at, created_at
`

type ListPriceUpdateCandidateProductsParams struct {
	Column1 string    `json:"column_1"`
	Column2 string    `json:"column_2"`
	Column3 time.Time `json:"column_3"`
}

type ListPriceUpdateCandidateProductsRow struct {
	ID                string    `json:"id"`
	Market            string    `json:"market"`
	ExternalProductID string    `json:"external_product_id"`
	OriginalUrl       string    `json:"original_url"`
	Title             string    `json:"title"`
	MainImageUrl      string    `json:"main_image_url"`
	ProductUrl        string    `json:"product_url"`
	CollectionSource  string    `json:"collection_source"`
	LastCollectedAt   time.Time `json:"last_collected_at"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

func (q *Queries) ListPriceUpdateCandidateProducts(ctx context.Context, arg ListPriceUpdateCandidateProductsParams) ([]ListPriceUpdateCandidateProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPriceUpdateCandidateProducts, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPriceUpdateCandidateProductsRow{}
	for rows.Next() {
		var i ListPriceUpdateCandidateProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Market,
			&i.ExternalProductID,
			&i.OriginalUrl,
			&i.Title,
			&i.MainImageUrl,
			&i.ProductUrl,
			&i.CollectionSource,
			&i.LastCollectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByCollectionSource = `-- name: ListProductsByCollectionSource :many
SELECT id, market, origin_product_id AS external_product_id, original_url, title, main_image_url,
       product_url, collection_source,
       last_collected_at, created_at, updated_at
FROM gugu.product
WHERE collection_source = $1
ORDER BY created_at
`

type ListProductsByCollectionSourceRow struct {
	ID                string    `json:"id"`
	Market            string    `json:"market"`
	ExternalProductID string    `json:"external_product_id"`
	OriginalUrl       string    `json:"original_url"`
	Title             string    `json:"title"`
	MainImageUrl      string    `json:"main_image_url"`
	ProductUrl        string    `json:"product_url"`
	CollectionSource  string    `json:"collection_source"`
	LastCollectedAt   time.Time `json:"last_collected_at"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

func (q *Queries) ListProductsByCollectionSource(ctx context.Context, collectionSource string) ([]ListProductsByCollectionSourceRow, error) {
	rows, err := q.db.QueryContext(ctx, listProductsByCollectionSource, collectionSource)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsByCollectionSourceRow{}
	for rows.Next() {
		var i ListProductsByCollectionSourceRow
		if err := rows.Scan(
			&i.ID,
			&i.Market,
			&i.ExternalProductID,
			&i.OriginalUrl,
			&i.Title,
			&i.MainImageUrl,
			&i.ProductUrl,
			&i.CollectionSource,
			&i.LastCollectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByMarket = `-- name: ListProductsByMarket :many
SELECT id, market, origin_product_id AS external_product_id, original_url, title, main_image_url,
       product_url, collection_source, last_collected_at, created_at, updated_at
FROM gugu.product
WHERE market = $1
ORDER BY created_at
`

type ListProductsByMarketRow struct {
	ID                string    `json:"id"`
	Market            string    `json:"market"`
	ExternalProductID string    `json:"external_product_id"`
	OriginalUrl       string    `json:"original_url"`
	Title             string    `json:"title"`
	MainImageUrl      string    `json:"main_image_url"`
	ProductUrl        string    `json:"product_url"`
	CollectionSource  string    `json:"collection_source"`
	LastCollectedAt   time.Time `json:"last_collected_at"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

func (q *Queries) ListProductsByMarket(ctx context.Context, market string) ([]ListProductsByMarketRow, error) {
	rows, err := q.db.QueryContext(ctx, listProductsByMarket, market)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsByMarketRow{}
	for rows.Next() {
		var i ListProductsByMarketRow
		if err := rows.Scan(
			&i.ID,
			&i.Market,
			&i.ExternalProductID,
			&i.OriginalUrl,
			&i.Title,
			&i.MainImageUrl,
			&i.ProductUrl,
			&i.CollectionSource,
			&i.LastCollectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsWithoutSKUs = `-- name: ListProductsWithoutSKUs :many
SELECT p.id, p.market, p.origin_product_id AS external_product_id, p.original_url, p.title,
       p.main_image_url, p.product_url,
       p.collection_source, p.last_collected_at, p.created_at, p.updated_at
FROM gugu.product p
LEFT JOIN gugu.sku s ON p.id = s.product_id
WHERE s.id IS NULL
ORDER BY p.created_at
`

type ListProductsWithoutSKUsRow struct {
	ID                string    `json:"id"`
	Market            string    `json:"market"`
	ExternalProductID string    `json:"external_product_id"`
	OriginalUrl       string    `json:"original_url"`
	Title             string    `json:"title"`
	MainImageUrl      string    `json:"main_image_url"`
	ProductUrl        string    `json:"product_url"`
	CollectionSource  string    `json:"collection_source"`
	LastCollectedAt   time.Time `json:"last_collected_at"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

func (q *Queries) ListProductsWithoutSKUs(ctx context.Context) ([]ListProductsWithoutSKUsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProductsWithoutSKUs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsWithoutSKUsRow{}
	for rows.Next() {
		var i ListProductsWithoutSKUsRow
		if err := rows.Scan(
			&i.ID,
			&i.Market,
			&i.ExternalProductID,
			&i.OriginalUrl,
			&i.Title,
			&i.MainImageUrl,
			&i.ProductUrl,
			&i.CollectionSource,
			&i.LastCollectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :execrows
UPDATE gugu.product
SET original_url = $2, title = $3, main_image_url = $4,
    product_url = $5, collection_source = $6, last_collected_at = $7, updated_at = $8
WHERE id = $1
`

type UpdateProductParams struct {
	ID               string    `json:"id"`
	OriginalUrl      string    `json:"original_url"`
	Title            string    `json:"title"`
	MainImageUrl     string    `json:"main_image_url"`
	ProductUrl       string    `json:"product_url"`
	CollectionSource string    `json:"collection_source"`
	LastCollectedAt  time.Time `json:"last_collected_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateProduct,
		arg.ID,
		arg.OriginalUrl,
		arg.Title,
		arg.MainImageUrl,
		arg.ProductUrl,
		arg.CollectionSource,
		arg.LastCollectedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
