// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_price_history.sql

package sqldb

import (
	"context"
	"database/sql"
	"time"
)

const getLatestProductPrice = `-- name: GetLatestProductPrice :one
SELECT product_id, recorded_at, price, currency, change_value, sku_id
FROM gugu.product_price_history
WHERE product_id = $1 AND currency = $2
ORDER BY recorded_at DESC
LIMIT 1
`

type GetLatestProductPriceParams struct {
	ProductID string `json:"product_id"`
	Currency  string `json:"currency"`
}

func (q *Queries) GetLatestProductPrice(ctx context.Context, arg GetLatestProductPriceParams) (GuguProductPriceHistory, error) {
	row := q.db.QueryRowContext(ctx, getLatestProductPrice, arg.ProductID, arg.Currency)
	var i GuguProductPriceHistory
	err := row.Scan(
		&i.ProductID,
		&i.RecordedAt,
		&i.Price,
		&i.Currency,
		&i.ChangeValue,
		&i.SkuID,
	)
	return i, err
}

const insertProductPriceHistory = `-- name: InsertProductPriceHistory :exec
INSERT INTO gugu.product_price_history (
    product_id, recorded_at, price, currency, change_value, sku_id
) VALUES (
    $1, $2, $3, $4, $5, $6
) ON CONFLICT (product_id, currency, recorded_at) DO NOTHING
`

type InsertProductPriceHistoryParams struct {
	ProductID   string         `json:"product_id"`
	RecordedAt  time.Time      `json:"recorded_at"`
	Price       string         `json:"price"`
	Currency    string         `json:"currency"`
	ChangeValue string         `json:"change_value"`
	SkuID       sql.NullString `json:"sku_id"`
}

func (q *Queries) InsertProductPriceHistory(ctx context.Context, arg InsertProductPriceHistoryParams) error {
	_, err := q.db.ExecContext(ctx, insertProductPriceHistory,
		arg.ProductID,
		arg.RecordedAt,
		arg.Price,
		arg.Currency,
		arg.ChangeValue,
		arg.SkuID,
	)
	return err
}

const upsertProductPriceSnapshot = `-- name: UpsertProductPriceSnapshot :exec
INSERT INTO gugu.product_price_snapshot (
    product_id, snapshot_date, price, currency
) VALUES (
    $1, $2, $3, $4
) ON CONFLICT (product_id, currency, snapshot_date) DO UPDATE SET
    price = EXCLUDED.price
`

type UpsertProductPriceSnapshotParams struct {
	ProductID    string    `json:"product_id"`
	SnapshotDate time.Time `json:"snapshot_date"`
	Price        string    `json:"price"`
	Currency     string    `json:"currency"`
}

func (q *Queries) UpsertProductPriceSnapshot(ctx context.Context, arg UpsertProductPriceSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, upsertProductPriceSnapshot,
		arg.ProductID,
		arg.SnapshotDate,
		arg.Price,
		arg.Currency,
	)
	return err
}
