// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_variant.sql

package sqldb

import (
	"context"
	"database/sql"
	"time"
)

const upsertProductVariant = `-- name: UpsertProductVariant :exec
INSERT INTO gugu.product_variant (
    product_id, language, currency, title, main_image_url, product_url,
    current_price, last_collected_at, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
ON CONFLICT (product_id, language, currency) DO UPDATE SET
    title = EXCLUDED.title,
    main_image_url = EXCLUDED.main_image_url,
    product_url = EXCLUDED.product_url,
    current_price = EXCLUDED.current_price,
    last_collected_at = EXCLUDED.last_collected_at,
    updated_at = EXCLUDED.updated_at
`

type UpsertProductVariantParams struct {
	ProductID       string       `json:"product_id"`
	Language        string       `json:"language"`
	Currency        string       `json:"currency"`
	Title           string       `json:"title"`
	MainImageUrl    string       `json:"main_image_url"`
	ProductUrl      string       `json:"product_url"`
	CurrentPrice    string       `json:"current_price"`
	LastCollectedAt sql.NullTime `json:"last_collected_at"`
	CreatedAt       time.Time    `json:"created_at"`
	UpdatedAt       time.Time    `json:"updated_at"`
}

func (q *Queries) UpsertProductVariant(ctx context.Context, arg UpsertProductVariantParams) error {
	_, err := q.db.ExecContext(ctx, upsertProductVariant,
		arg.ProductID,
		arg.Language,
		arg.Currency,
		arg.Title,
		arg.MainImageUrl,
		arg.ProductUrl,
		arg.CurrentPrice,
		arg.LastCollectedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
