// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sku_price_history.sql

package sqldb

import (
	"context"
	"time"
)

const getLatestSKUPrice = `-- name: GetLatestSKUPrice :one
SELECT sku_id, recorded_at, price, currency, change_value
FROM gugu.sku_price_history
WHERE sku_id = $1 AND currency = $2
ORDER BY recorded_at DESC
LIMIT 1
`

type GetLatestSKUPriceParams struct {
	SkuID    string `json:"sku_id"`
	Currency string `json:"currency"`
}

func (q *Queries) GetLatestSKUPrice(ctx context.Context, arg GetLatestSKUPriceParams) (GuguSkuPriceHistory, error) {
	row := q.db.QueryRowContext(ctx, getLatestSKUPrice, arg.SkuID, arg.Currency)
	var i GuguSkuPriceHistory
	err := row.Scan(
		&i.SkuID,
		&i.RecordedAt,
		&i.Price,
		&i.Currency,
		&i.ChangeValue,
	)
	return i, err
}

const insertSKUPriceHistory = `-- name: InsertSKUPriceHistory :exec
INSERT INTO gugu.sku_price_history (
    sku_id, recorded_at, price, currency, change_value
) VALUES (
    $1, $2, $3, $4, $5
) ON CONFLICT (sku_id, currency, recorded_at) DO NOTHING
`

type InsertSKUPriceHistoryParams struct {
	SkuID       string    `json:"sku_id"`
	RecordedAt  time.Time `json:"recorded_at"`
	Price       string    `json:"price"`
	Currency    string    `json:"currency"`
	ChangeValue string    `json:"change_value"`
}

func (q *Queries) InsertSKUPriceHistory(ctx context.Context, arg InsertSKUPriceHistoryParams) error {
	_, err := q.db.ExecContext(ctx, insertSKUPriceHistory,
		arg.SkuID,
		arg.RecordedAt,
		arg.Price,
		arg.Currency,
		arg.ChangeValue,
	)
	return err
}

const upsertSKUPriceSnapshot = `-- name: UpsertSKUPriceSnapshot :exec
INSERT INTO gugu.sku_price_snapshot (
    sku_id, snapshot_date, price, original_price, currency
) VALUES (
    $1, $2, $3, $4, $5
) ON CONFLICT (sku_id, currency, snapshot_date) DO UPDATE SET
    price = EXCLUDED.price,
    original_price = EXCLUDED.original_price
`

type UpsertSKUPriceSnapshotParams struct {
	SkuID         string    `json:"sku_id"`
	SnapshotDate  time.Time `json:"snapshot_date"`
	Price         string    `json:"price"`
	OriginalPrice string    `json:"original_price"`
	Currency      string    `json:"currency"`
}

func (q *Queries) UpsertSKUPriceSnapshot(ctx context.Context, arg UpsertSKUPriceSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, upsertSKUPriceSnapshot,
		arg.SkuID,
		arg.SnapshotDate,
		arg.Price,
		arg.OriginalPrice,
		arg.Currency,
	)
	return err
}
