// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqldb

import (
	"context"
	"time"
)

const countAdminUsers = `-- name: CountAdminUsers :one
SELECT COUNT(*)
FROM gugu.app_user u
WHERE (
    $1::text = ''
    OR u.email ILIKE '%' || $1 || '%'
    OR u.display_name ILIKE '%' || $1 || '%'
)
AND (
    $2::text = ''
    OR ($2::text = 'FREE')
)
AND (
    $3::text = ''
    OR (
        $3::text = 'ACTIVE'
        AND COALESCE((
            SELECT MAX(oi.last_login_at)
            FROM gugu.oauth_identity oi
            WHERE oi.user_id = u.id
        ), '0001-01-01 00:00:00+00'::timestamptz) >= $4
    )
    OR (
        $3::text = 'INACTIVE'
        AND COALESCE((
            SELECT MAX(oi.last_login_at)
            FROM gugu.oauth_identity oi
            WHERE oi.user_id = u.id
        ), '0001-01-01 00:00:00+00'::timestamptz) < $4
    )
)
`

type CountAdminUsersParams struct {
	Column1     string    `json:"column_1"`
	Column2     string    `json:"column_2"`
	Column3     string    `json:"column_3"`
	LastLoginAt time.Time `json:"last_login_at"`
}

func (q *Queries) CountAdminUsers(ctx context.Context, arg CountAdminUsersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminUsers,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.LastLoginAt,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listAdminUsers = `-- name: ListAdminUsers :many
SELECT
    u.id,
    u.email,
    u.display_name,
    u.email_verified,
    u.created_at,
    COALESCE((
        SELECT COUNT(*)::bigint
        FROM gugu.user_tracked_item uti
        WHERE uti.user_id = u.id
          AND uti.deleted_at IS NULL
    ), 0)::bigint AS tracked_item_count,
    (
        SELECT MAX(oi.last_login_at)
        FROM gugu.oauth_identity oi
        WHERE oi.user_id = u.id
    ) AS last_login_at,
    'FREE'::text AS plan,
    CASE
        WHEN COALESCE((
            SELECT MAX(oi.last_login_at)
            FROM gugu.oauth_identity oi
            WHERE oi.user_id = u.id
        ), '0001-01-01 00:00:00+00'::timestamptz) >= $4 THEN 'ACTIVE'::text
        ELSE 'INACTIVE'::text
    END AS status
FROM gugu.app_user u
WHERE (
    $1::text = ''
    OR u.email ILIKE '%' || $1 || '%'
    OR u.display_name ILIKE '%' || $1 || '%'
)
AND (
    $2::text = ''
    OR ($2::text = 'FREE')
)
AND (
    $3::text = ''
    OR (
        $3::text = 'ACTIVE'
        AND COALESCE((
            SELECT MAX(oi.last_login_at)
            FROM gugu.oauth_identity oi
            WHERE oi.user_id = u.id
        ), '0001-01-01 00:00:00+00'::timestamptz) >= $4
    )
    OR (
        $3::text = 'INACTIVE'
        AND COALESCE((
            SELECT MAX(oi.last_login_at)
            FROM gugu.oauth_identity oi
            WHERE oi.user_id = u.id
        ), '0001-01-01 00:00:00+00'::timestamptz) < $4
    )
)
ORDER BY u.created_at DESC
LIMIT $5 OFFSET $6
`

type ListAdminUsersParams struct {
	Column1     string    `json:"column_1"`
	Column2     string    `json:"column_2"`
	Column3     string    `json:"column_3"`
	LastLoginAt time.Time `json:"last_login_at"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

type ListAdminUsersRow struct {
	ID               string      `json:"id"`
	Email            string      `json:"email"`
	DisplayName      string      `json:"display_name"`
	EmailVerified    bool        `json:"email_verified"`
	CreatedAt        time.Time   `json:"created_at"`
	TrackedItemCount int64       `json:"tracked_item_count"`
	LastLoginAt      interface{} `json:"last_login_at"`
	Plan             string      `json:"plan"`
	Status           string      `json:"status"`
}

func (q *Queries) ListAdminUsers(ctx context.Context, arg ListAdminUsersParams) ([]ListAdminUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listAdminUsers,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.LastLoginAt,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminUsersRow{}
	for rows.Next() {
		var i ListAdminUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.EmailVerified,
			&i.CreatedAt,
			&i.TrackedItemCount,
			&i.LastLoginAt,
			&i.Plan,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
